[project]
name = "hawkeye-28-loads"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=3.0.5,<4.0.0)",
    "numpy (>=2.5.2,<3.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)",
    "pytest (>=9.1.1,<10.0.0)"
]

[tool.poetry]
packages = [{include = "hawkeye_28_loads", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.3.0,<8.0.0)"
]
